---
- name: springboot as linux
  hosts: appserver
  become: yes

  tasks:
    - name: fail the execution when the distribution is not ubuntu
      fail:
        msg: "This playbook will only work for ubuntu distribution and support for other os will be added soon"
      when: ansible_facts['distribution'] != "Ubuntu"
    - name: debug message for java
      debug:
        msg: "java with version {{java_package}} is installed on the insance"
    - name: updating the ubuntu packages and installing the java package 
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present 
    - name: creating a directory 
      file:
        path: "{{ app_dir }}"
        state: directory
    - name: download the springpet clinic jar file 
      get_url:
        url: "{{ app_download_url }}"
        dest: "{{ app_file_name }}"
    - name: adding the springbootuser 
      user:
        name: springbootuser
        password: springbootuser
        state: present 
    - name: changing the ownership of file and directory
      file:
        path: "{{ app_file_name }}"
        owner: "{{ app_username }}"
        group: "{{ app_username }}"
        mode: '500'
        state: file
    - name: copying the springpetclinic service file 
      copy: 
        src: /home/devops/practice_springboot/springpetclinic.service
        dest: /etc/systemd/system/springpetclinic.service
    - name: enable and start the springpetclinic service 
      systemd:
        name: springpetclinic.service 
        state: started
        enabled: yes