---
- name: springboot as linux
  hosts: appserver
  become: yes
  vars: 
    java_package: openjdk-11-jdk
    app_dir: /usr/share/springpetclinic
    app_download_url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
    app_file_name: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    app_username: springbootuser
    test_var: just for testing 
  tasks:
    - name: Display the java package 
      debug:
        var: java_package
    - name: Checking variables
      debug:
        var: test_var
    - name: updating the ubuntu packages and installing the java package 
      apt:
        name: {{ java_package }} 
        update_cache: yes
        state: present 
    - name: creating a directory 
      file:
        path: {{app_dir}}
        state: directory
    - name: download the springpet clinic jar file 
      get_url:
        url: {{app_download_url}}
        dest: {{app_file_name}}
    - name: adding the springbootuser 
      user:
        name: springbootuser
        password: springbootuser
        state: present 
    - name: changing the ownership of file and directory
      file:
        path: {{app_file_name}}
        owner: {{app_username}}
        group: {{app_username}}
        mode: '500'
        state: file
    - name: copying the springpetclinic service file 
      copy: 
        src: /home/devops/practice_springboot/springpetclinic.service
        dest: /etc/systemd/system/springpetclinic.service
    - name: enable and start the springpetclinic service 
      systemd:
        name: springpetclinic.service 
        state: started
        enabled: yes